// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: proto/Students.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStudentListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname     string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Id          int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Yearofstudy int32  `protobuf:"varint,4,opt,name=yearofstudy,proto3" json:"yearofstudy,omitempty"`
	Marks       int32  `protobuf:"varint,5,opt,name=Marks,proto3" json:"Marks,omitempty"`
	Subjects    int32  `protobuf:"varint,6,opt,name=Subjects,proto3" json:"Subjects,omitempty"`
}

func (x *GetStudentListRequest) Reset() {
	*x = GetStudentListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Students_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentListRequest) ProtoMessage() {}

func (x *GetStudentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Students_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentListRequest.ProtoReflect.Descriptor instead.
func (*GetStudentListRequest) Descriptor() ([]byte, []int) {
	return file_proto_Students_proto_rawDescGZIP(), []int{0}
}

func (x *GetStudentListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStudentListRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *GetStudentListRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetStudentListRequest) GetYearofstudy() int32 {
	if x != nil {
		return x.Yearofstudy
	}
	return 0
}

func (x *GetStudentListRequest) GetMarks() int32 {
	if x != nil {
		return x.Marks
	}
	return 0
}

func (x *GetStudentListRequest) GetSubjects() int32 {
	if x != nil {
		return x.Subjects
	}
	return 0
}

type GetStudentsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpa int32 `protobuf:"varint,1,opt,name=Gpa,proto3" json:"Gpa,omitempty"`
}

func (x *GetStudentsListResponse) Reset() {
	*x = GetStudentsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Students_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudentsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsListResponse) ProtoMessage() {}

func (x *GetStudentsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Students_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsListResponse.ProtoReflect.Descriptor instead.
func (*GetStudentsListResponse) Descriptor() ([]byte, []int) {
	return file_proto_Students_proto_rawDescGZIP(), []int{1}
}

func (x *GetStudentsListResponse) GetGpa() int32 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

var File_proto_Students_proto protoreflect.FileDescriptor

var file_proto_Students_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x01,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x79, 0x65, 0x61, 0x72, 0x6f, 0x66, 0x73,
	0x74, 0x75, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x79, 0x65, 0x61, 0x72,
	0x6f, 0x66, 0x73, 0x74, 0x75, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x72, 0x6b, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x2b, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x70, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x47, 0x70, 0x61, 0x32, 0x58, 0x0a, 0x08, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x4c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_Students_proto_rawDescOnce sync.Once
	file_proto_Students_proto_rawDescData = file_proto_Students_proto_rawDesc
)

func file_proto_Students_proto_rawDescGZIP() []byte {
	file_proto_Students_proto_rawDescOnce.Do(func() {
		file_proto_Students_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Students_proto_rawDescData)
	})
	return file_proto_Students_proto_rawDescData
}

var file_proto_Students_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_Students_proto_goTypes = []interface{}{
	(*GetStudentListRequest)(nil),   // 0: proto.GetStudentListRequest
	(*GetStudentsListResponse)(nil), // 1: proto.GetStudentsListResponse
}
var file_proto_Students_proto_depIdxs = []int32{
	0, // 0: proto.Students.GetStudent:input_type -> proto.GetStudentListRequest
	1, // 1: proto.Students.GetStudent:output_type -> proto.GetStudentsListResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Students_proto_init() }
func file_proto_Students_proto_init() {
	if File_proto_Students_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Students_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudentListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Students_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudentsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Students_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Students_proto_goTypes,
		DependencyIndexes: file_proto_Students_proto_depIdxs,
		MessageInfos:      file_proto_Students_proto_msgTypes,
	}.Build()
	File_proto_Students_proto = out.File
	file_proto_Students_proto_rawDesc = nil
	file_proto_Students_proto_goTypes = nil
	file_proto_Students_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StudentsClient is the client API for Students service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentsClient interface {
	GetStudent(ctx context.Context, in *GetStudentListRequest, opts ...grpc.CallOption) (*GetStudentsListResponse, error)
}

type studentsClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentsClient(cc grpc.ClientConnInterface) StudentsClient {
	return &studentsClient{cc}
}

func (c *studentsClient) GetStudent(ctx context.Context, in *GetStudentListRequest, opts ...grpc.CallOption) (*GetStudentsListResponse, error) {
	out := new(GetStudentsListResponse)
	err := c.cc.Invoke(ctx, "/proto.Students/GetStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentsServer is the server API for Students service.
type StudentsServer interface {
	GetStudent(context.Context, *GetStudentListRequest) (*GetStudentsListResponse, error)
}

// UnimplementedStudentsServer can be embedded to have forward compatible implementations.
type UnimplementedStudentsServer struct {
}

func (*UnimplementedStudentsServer) GetStudent(context.Context, *GetStudentListRequest) (*GetStudentsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudent not implemented")
}

func RegisterStudentsServer(s *grpc.Server, srv StudentsServer) {
	s.RegisterService(&_Students_serviceDesc, srv)
}

func _Students_GetStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServer).GetStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Students/GetStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServer).GetStudent(ctx, req.(*GetStudentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Students_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Students",
	HandlerType: (*StudentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudent",
			Handler:    _Students_GetStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/Students.proto",
}
